---
name: SVK-Log-Filter-Babelfish
version: !!perl/hash:Module::Build::Version
  original: 0.0.2
  qv: 1
  version:
    - 0
    - 0
    - 2
author:
  - 'Michael Hendricks <michael@ndrix.org>'
abstract: translate logs to various natural languages
license: mit
resources:
  license: http://opensource.org/licenses/mit-license.php
requires:
  SVK: 1.99
  WWW::Babelfish: 0.13
build_requires:
  Test::More: 0
provides:
  SVK::Log::Filter::Babelfish:
    file: lib/SVK/Log/Filter/Babelfish.pm
    version: 0.0.2
generated_by: Module::Build version 0.2804
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
